# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-base:testing"


command:

  build:
    - composer update


  #- some link
  - vbendor bin
  dev:
  - some prog